// Generated by CoffeeScript 1.6.2
(function() {
  var app, express, mongo;

  express = require('express');

  mongo = require('./routes/mongo');

  app = express();

  app.set('title', 'Grades');

  app.use(express.compress());

  app.use('/', express["static"](__dirname + '/public', {
    maxAge: 86400
  }));

  app.use(express.bodyParser());

  app.use(express.logger());

  app.post('/login', mongo.login);

  app.post('/update', mongo.update);

  app.post('/forgot', mongo.forgot);

  app.listen(process.env.PORT || 3000);

}).call(this);
